package uy.com.netlabs.luthier.veditor

import scala.tools.nsc.interactive.Global

/**
 * Description of a flow generated by FlowAnalyzer.
 */
case class FlowDescriptor(flowName: String,
                          rootEndpoint: String,
                          exchangePattern: String,
                          rootMessageType: String,
                          expectedResponseType: Option[String],
                          srcPosition: Global#Position)
